// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"webLoader","status":false,"description":"Test your project in your default browser","parameters":{"aldb":"true"}},
{"name":"AudioStreaming","status":true,"description":"Load audio faster and use only ogg files.","parameters":{"mode":"10"}},
{"name":"N_Audio","status":true,"description":"","parameters":{}}
];
