// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"stbvorbis_stream","status":false,"description":"","parameters":{}},
{"name":"AudioStreaming","status":true,"description":"Load audio faster and use only ogg files.","parameters":{"mode":"11","deleteM4a":"false"}},
{"name":"N_X_AudioStreaming","status":true,"description":"v1.01 (Requires AudioStreaming) Move audio decoding to audio worklet.","parameters":{}}
];
